version: '3'
services:
  web:
    build: .
    image: rails

    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - node_modules:/app/node_modules
      - .:/app:cached
      - packs:/app/public/packs
      - bundle:/usr/local/bundle
      - tmp:/app/tmp

    environment:
      RAILS_ENV: 'development'
      REDIS_URL: 'redis://redis:6379/0'
    ports:
      - '3000:3000'
  redis:
    image: redis
  sidekiq:
    image: rails
    command: 'bundle exec sidekiq'
    volumes:
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - bundle:/usr/local/bundle
      - .:/app:cached

    environment:
      RAILS_ENV: 'development'
      REDIS_URL: 'redis://redis:6379/0'
    depends_on:
      - redis
      - web

  webpack:
    image: rails
    command: './bin/webpack -w'
    volumes:
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - .:/app:cached
      - tmp:/app/tmp
      - bundle:/usr/local/bundle

    environment:
      RAILS_ENV: 'development'
      REDIS_URL: 'redis://redis:6379/0'
    depends_on:
      - redis
      
volumes:
  node_modules:
  packs:
  tmp:
  bundle:
